[project]
name = "masterthesis-llm-testing"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "openai>=1.40",          
  "pydantic>=2.7",
  "pydantic-settings>=2.3",
  "jinja2>=3.1",
  "python-dotenv>=1.0",
  "pyyaml>=6.0",
  "typer>=0.12",
  "rich>=13.7"
]
